# Generated by Django 4.1.5 on 2023-01-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_condo'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
