# Generated by Django 4.1.5 on 2023-01-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_condo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
