# Generated by Django 4.1.5 on 2023-01-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_condo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='image',
        ),
        migrations.AddField(
            model_name='condo',
            name='condo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
