# Generated by Django 4.1.5 on 2023-02-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_remove_condo_image_condo_condo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_service', models.FloatField()),
                ('build_quality', models.FloatField()),
                ('amenities', models.FloatField()),
                ('location', models.FloatField()),
                ('would_reviewer_recommend', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.condo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
