# Generated by Django 4.1.5 on 2023-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
