# Generated by Django 4.1.5 on 2023-02-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reviewrating_review_reviewrating_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='build_quality',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='would_reviewer_recommend',
        ),
    ]
