# Generated by Django 4.1.5 on 2023-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_reviewrating_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='amenities',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='build_quality',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='location',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
