# Generated by Django 4.1.5 on 2023-02-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reviewrating_amenities_reviewrating_build_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='condo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.condo'),
        ),
    ]
