# Generated by Django 4.1.5 on 2023-02-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_reviewrating_condo'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='pet_friendly',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
