# Generated by Django 4.1.5 on 2023-02-26 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_condo_pet_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='built_in',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)]),
            preserve_default=False,
        ),
    ]
