# Generated by Django 4.1.5 on 2023-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_condo_built_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='content',
        ),
        migrations.AddField(
            model_name='condo',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condo',
            name='architect',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condo',
            name='developer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condo',
            name='floors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condo',
            name='number_of_units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='would_reviewer_recommend',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
