# Generated by Django 4.1.5 on 2023-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_condo_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='developer',
            field=models.CharField(max_length=255),
        ),
    ]
