# Generated by Django 4.1.5 on 2023-02-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_condo_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.developer'),
        ),
    ]
