# Generated by Django 4.1.5 on 2023-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_condo_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='city',
            field=models.CharField(default='Vancouver', max_length=255),
            preserve_default=False,
        ),
    ]
